### ISSUE TITLE
Deprecate type and coerce when necessary

### ISSUE THREAD

**Issue by peterdesmet** [inbo/pywhip#24]
Currently, the user needs to define `type` before certain tests can pass (e.g. `min` or `max`).

It would be more intuitive if e.g. a `min` specification did not require a `type` specification, but instead tried to:

1. Coerce the input value (considered a string) to the required type (a `number`)
2. Then test the `min` specification

The reporting could indicate at which step the test failed.

Effects:

* `type: json` and `type: url` need to become `stringformat: json` and `stringformat: url`
* `type: boolean` is no longer supported, but that was a tricky one anyway, as it can be coerced in non-intuitive ways. User can use `allowed: [0, 1, True, False]` instead.
* Number tests no longer require a `type`
* Difference between integers and floats can be tested with `numberformat`
* `type: string` was useless anyway, as every value passed it.

**Comment by peterdesmet** [comment]
@stijnvanhoey, in the specifications [you wrote](https://github.com/inbo/whip/commit/33527deae8ff0e2351c7eac0f372ba7d43979f4d#diff-af643778edca98c198bc5decd4bcfaf1R117):

> **Remark:**
> 
> The behaviour of length (`minlength` and `maxlength`) depends on the usage of the `length` validation in combination with the `type` validation or not. When no `type` validation is added (or tests for string, which is default), the length will interpret the field as string:
> 
> ```YAML
> maxlength: 2  
> type : string  
> ```
> will invoke an error for the field : `{'individualCount' : '100'}`. However, when requiring an integer value:
> 
> ```YAML
> maxlength: 2
> type : integer
> ```
> the field `{'individualCount' : '100'}` will be converted to `{'individualCount' : 100}` (100 as  integer) and `length` will ignore the integer. It makes more sense to test this with the `min` and `max` validators (see further).

I have removed that whole section. I think `minlength` and `maxlength` should always assume strings and test for those.

**Comment by stijnvanhoey** [comment]
`type` has been removed from the specification, closing here
