### ISSUE TITLE
Make sure regex is full match to pass

### ISSUE THREAD

**Issue by peterdesmet** [inbo/pywhip#27]
```yaml
occurrenceid:
  regex: \d{3,4}:\d{8}
```

Should always be a **full match** on the total value to pass:

```
123:12345678
1234:12345678
1234:123456789 # should fail, even though part of that string passes
12345:123456788 # should fail, even though part of that string passes
```

Best to also indicate [this in syntax](https://github.com/inbo/whip/blob/master/docs/syntax.md)

**Comment by stijnvanhoey** [comment]
To make sure the examples work, it is actually a matter of adapting the regex itself:

```yaml
occurrenceid:
  regex: ^\d{3,4}:\d{8}$
```
I would not do some *automated* pre-processing of the regex behind the screens as we will actually miss the whole point/power of regex-expressions. Sometimes the user will be fine with a partial match, sometimes with a full match. Adding the advice of the `^` (start of string) and `$` (end of string) possibility in the docs will be more worthwhile I think.

**Comment by stijnvanhoey** [comment]
Appears to be an issue on cerberus as well, see https://github.com/pyeve/cerberus/issues/169 and has actually to do with the behaviour of the `regex` package of Python:

```
Signature: re.match(pattern, string, flags=0)
Docstring:
Try to apply the pattern at the start of the string, returning
a match object, or None if no match was found.
...
```

**Comment by peterdesmet** [comment]
Has this been updated in the syntax?

**Comment by stijnvanhoey** [comment]
In the syntax:

```
Note: The regex always expects to have a full match of the value.
```
