### ISSUE TITLE
Format HTML report

### ISSUE THREAD

**Issue by peterdesmet** [inbo/pywhip#49]
# Whip validator report

Date: ...

## Summary

Total rows: 
Rows passed: 
General warnings:

- ...
- ...

Unspecified fields:

- ...
- ...

Unknown fields:

- ...
- ...

## Specifications

Field | Specification | Percentage passed
--- | --- | ---
basisOfRecord | allowed | 100
basisOfRecord | allowed_if_1 | 99
decimalLatitude | max | 100
decimalLatitude | min | 3

#### allowed

constraint: `[HumanObservation, MachineObservation]`

Value | First row | Message | # rows failed
--- | --- | --- | ---
human | 1 | unallowed value human | 34

**Comment by stijnvanhoey** [comment]
We have adapted the format by integrating the examples inside the main overview using dropdown. As such, closing here.
